env:
  global:
    secure: "s++NjwLU5F9EHOLOhtKvGKQuvxHDM8cPbVjtoR9EVszbdASRLAJ1Vwg8xUc7K6mlmbsSpNvFdUX/tU16inz26O6VDOycnOQlEUnAJ4mTaf3n7NEwdTO1eFqps45TX1Zy0z0UTcBLybBYULq/TASYN7FhBjvuIknMEwrZmoTzjBwdxCdO0OoYlDGCtdXmty/f9btz/DJuoWrSzFa/onxKCn0hAONfl4C4b/+15SpDrbsScT3sWMeXR1JjK5kFjGm+druSvl1AKWICopvDFNi9jzwBo/OpMCij0fSvckXEgHBjDWL2WjE5VVfW+TYwTCUkjAAJAFH/YmvlaMnYAfkEOio0gmvrOXFg7t8Wn0w+edSblAa36UWzvZIFTPPW8pMIWoA+JEURUM2DyNhFmvoVuXUs9g1uh0QWKKCSE76Vxe600GSfX8dJIHVEkACsyhkutnfuYY1AX+1ueE8d/en90qKwovCKrUr9fZKJSuXQL9yrhXb7f9O1qx14xKCiLM05Gq6jV9UdMaF9KlmOXAXCtvZ35nKZUNnr9kyKcPZh9Cd5NY3JDbG06gse8yaIZomzCI1+1975JZ+EMRbhz0nLnv9qMA9HYjYXY63+P2JyDNgtwrlYMszRBDxhPpux6gVL3zds99uKkLwSjU9Q1jtUd7Bf8y2MxjRy7kXhFoFKREo="
language: java
jdk: oraclejdk8
install:
  - git config --global user.email "travis@sw4j.org"
  - git config --global user.name "travis-ci"
script: mvn clean install
after_success: mvn post-site scm-publish:publish-scm
